# Generated by Django 3.0.6 on 2020-07-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosapp', '0003_clientdocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('days_to_completion', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosapp.Client')),
            ],
        ),
    ]
