# Generated by Django 3.0.6 on 2020-07-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosapp', '0007_auto_20200716_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosapp.Client')),
            ],
        ),
    ]
