# Generated by Django 3.0.6 on 2020-08-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosapp', '0008_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtsessions',
            name='url_mosgorsud',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judicialacts',
            name='url_mosgorsud',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statemovement',
            name='url_mosgorsud',
            field=models.CharField(default='', max_length=200),
        ),
    ]
