# Generated by Django 3.0.6 on 2020-08-20 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosapp', '0009_auto_20200820_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsessions',
            name='url_mosgorsud',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='judicialacts',
            name='url_mosgorsud',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='statemovement',
            name='url_mosgorsud',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UrlMosgorsud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_mosgorsud', models.CharField(max_length=200)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosapp.Client')),
            ],
        ),
    ]
