# Generated by Django 3.0.6 on 2020-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosapp', '0010_auto_20200820_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsessions',
            name='hall',
            field=models.CharField(max_length=200),
        ),
    ]
