# Generated by Django 3.0.6 on 2020-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosapp', '0011_auto_20200827_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
